spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer
    producer:
      client-id: message-publisher
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
      properties:
        cloudevents.serializer.encoding: STRUCTURED
        cloudevents.serializer.event_format: application/cloudevents+json
