spring:
  output.ansi.enabled: ALWAYS
  application.name: web-auto-instrumentation
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
#otel:
#  instrumentation:
#    spring-integration:
#      producer:
#        enabled: true
#
#  experimental:
#    sdk:
#      metrics:
#        debug: true

management.endpoints:
    web.exposure.include: "*"

logging:
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX,UTC
    console: "%clr(%d{${logging.pattern.dateformat}}){faint} %clr(%5p) %clr([${spring.application.name:-},%X{trace_id},%X{span_id},%X{trace_flags}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.20t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    com.tng.cloud: DEBUG